### ISSUE TITLE
FeatureRequest: Your Name

### ISSUE THREAD

**Issue by alvtsky** [ratsky-oss/sshabu#10]
**Is your feature request related to a problem? Please describe.**
Same hosts names in different groups leads to error 

**Describe the solution you'd like**
As a solution auto-append group name to host

**Comment by alvtsky** [comment]
```
- Name: Jon
   Options:
     User: root
     IdentityFile: ~/.ssh/id_rsa_mp
   Hosts:
     - Name: db-1
       HostName: 192.168.1.1

 - Name: Milandr
   Options:
     User: nshvora
     IdentityFile: ~/.ssh/id_rsa_mp
   Hosts:
     - Name: db-1
       HostName: 127.0.0.1

```

Could lead to warning and be solved as 

WARNING: same names in different groups: rename db-1 to Jon-db-1 Milandr-db-1
```
Host Jon-db-1
  Hostname: 192.168.1.1
  IdentityFile ~/.ssh/id_rsa_mp
  User root

Host Milandr-db-1
  Hostname: 127.0.0.1
  IdentityFile ~/.ssh/id_rsa_mp
  User nshvora
...
